#!/usr/bin/env bash
# script that sets nginx in a web server and returns "hello World" to STDOUT

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx restart
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
