#!/usr/bin/env bash
# script that sets nginx in a web server and returns "hello World" to STDOUT
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
