#!/usr/bin/env bash
# script that sets nginx in a web server and returns "hello World" to STDOUT
apt-get -y update
apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /etc/nginx/html/custom_404.html
sed -i '/server_name _;/a error_page 404 /etc/nginx/html/custom_404.html;' /etc/nginx/sites-available/default
service nginx start
