#!/usr/bin/env bash
# Sets user in server as "nginx",restarts service
chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
su nginx -c "service nginx restart" 
